apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hospital-app
  namespace: argocd
spec:
  project: default

  source:
    # GitHub Pages URL (Helm repository)
    repoURL: https://github.com/waglesaurav1/Hospital-web
    path: charts/hospital-chart
    # Deploy latest released chart version
    targetRevision: main  # it will deploy the latest version of the chart available in the helm repository
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: hospital-ns 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
